declare function validUsername(username: string): Error | null;
declare function validPassword(password: string): Error | null;
declare function validEmail(email: string): Error | null;
declare function validPhone(phone: string): Error | null;
declare function generateSalt(): string;
declare function hashPassword(password: string, salt: string): string;
declare function validatePassword(user: any, password: string): boolean;
declare function generateToken(user: any): any;
declare function isValidToken(token: any): boolean;
declare function createUsernameFromEmail(email: string): Promise<string>;
declare function isValidAccountUpdateTime(time: string): boolean;
declare function getFacebookDetails(accessToken: string): Promise<any>;
declare function getFacebookId(accessToken: string): Promise<any>;
declare function verifyGoogleIdToken(accessToken: string): Promise<any>;
declare const _default: {
    generateSalt: typeof generateSalt;
    hashPassword: typeof hashPassword;
    validatePassword: typeof validatePassword;
    generateToken: typeof generateToken;
    getFacebookDetails: typeof getFacebookDetails;
    getFacebookId: typeof getFacebookId;
    validUsername: typeof validUsername;
    validPassword: typeof validPassword;
    optionalAuth: (req: any, res: any, next: any) => void;
    requiredAuth: (req: any, res: any, next: any) => void;
    localAuth: (req: any, res: any, next: any) => void;
    validEmail: typeof validEmail;
    validPhone: typeof validPhone;
    isValidToken: typeof isValidToken;
    createUsernameFromEmail: typeof createUsernameFromEmail;
    verifyGoogleIdToken: typeof verifyGoogleIdToken;
    isValidAccountUpdateTime: typeof isValidAccountUpdateTime;
};
export default _default;
