declare const _default: {
    addAccount: typeof addAccount;
    getAccountByEmail: typeof getAccountByEmail;
    getAccountByUsername: typeof getAccountByUsername;
    deleteAccount: typeof deleteAccount;
    changePassword: typeof changePassword;
    getAccountById: typeof getAccountById;
    addFacebookAccount: typeof addFacebookAccount;
    getFacebookAccount: typeof getFacebookAccount;
    updateUsername: typeof updateUsername;
    connectFacebookAccount: typeof connectFacebookAccount;
    disconnectFacebookAccount: typeof disconnectFacebookAccount;
    addAccountMetadata: typeof addAccountMetadata;
    getAccountMetadata: typeof getAccountMetadata;
    updateAccountsMetadataDistanceUnit: typeof updateAccountsMetadataDistanceUnit;
    updateAccountsMetadataSearchDistance: typeof updateAccountsMetadataSearchDistance;
    updateAccountsMetadataSearchType: typeof updateAccountsMetadataSearchType;
    verifyAccount: typeof verifyAccount;
    usernameExists: typeof usernameExists;
    getGoogleAccount: typeof getGoogleAccount;
    addGoogleAccount: typeof addGoogleAccount;
    updateEmail: typeof updateEmail;
    updatePhone: typeof updatePhone;
    connectGoogleAccount: typeof connectGoogleAccount;
    disconnectGoogleAccount: typeof disconnectGoogleAccount;
    updateAccountsMetadataMatureFilter: typeof updateAccountsMetadataMatureFilter;
    updateAccountsMetadataThemeWeb: typeof updateAccountsMetadataThemeWeb;
    getAccountByEmailWithPass: typeof getAccountByEmailWithPass;
    getAccountByUsernameWithPass: typeof getAccountByUsernameWithPass;
};
export default _default;
declare function addAccountMetadata(accountId: string): Promise<any>;
declare function getAccountMetadata(accountId: string): Promise<any>;
declare function updateAccountsMetadataDistanceUnit(accountId: string, distanceUnit: string): Promise<any>;
declare function updateAccountsMetadataSearchDistance(accountId: string, searchDistance: string): Promise<any>;
declare function updateAccountsMetadataSearchType(accountId: string, searchType: string): Promise<any>;
declare function updateAccountsMetadataMatureFilter(accountId: string, matureFilter: boolean): Promise<any>;
declare function updateAccountsMetadataThemeWeb(accountId: string, themeWeb: boolean): Promise<any>;
declare function addAccount(email: string, username: string, pass: string, phone: string, salt: string): Promise<any>;
declare function getAccountByEmail(email: string): Promise<any>;
declare function getAccountByUsername(username: string): Promise<any>;
declare function getAccountByEmailWithPass(email: string): Promise<any>;
declare function getAccountByUsernameWithPass(username: string): Promise<any>;
declare function getAccountById(id: string): any;
declare function deleteAccount(accountId: string): any;
declare function updateUsername(username: string, accountId: string): any;
declare function usernameExists(username: string): any;
declare function updateEmail(email: string, accountId: string): any;
declare function updatePhone(phone: string, accountId: string): any;
declare function changePassword(account_id: string, password: string, salt: string): any;
declare function verifyAccount(account_id: string, date: Date): any;
declare function getFacebookAccount(facebookId: string): Promise<any>;
declare function addFacebookAccount(id: string, email: string, username: string): Promise<any>;
declare function connectFacebookAccount(facebookId: string, accountId: string): Promise<any>;
declare function disconnectFacebookAccount(accountId: string): Promise<any>;
declare function getGoogleAccount(googleId: string): Promise<any>;
declare function addGoogleAccount(id: string, email: string, username: string): Promise<any>;
declare function connectGoogleAccount(googleId: string, accountId: string): Promise<any>;
declare function disconnectGoogleAccount(accountId: string): Promise<any>;
