export { addAccount, getAccountByEmail, getAccountByUsername, deleteAccount, changePassword, getAccountById, addFacebookAccount, getFacebookAccount, updateUsername, connectFacebookAccount, disconnectFacebookAccount, addAccountMetadata, getAccountMetadata, updateAccountsMetadataDistanceUnit, updateAccountsMetadataSearchDistance, updateAccountsMetadataSearchType, verifyAccount, usernameExists, getGoogleAccount, addGoogleAccount, updateEmail, updatePhone, connectGoogleAccount, disconnectGoogleAccount, updateAccountsMetadataMatureFilter, updateAccountsMetadataThemeWeb, getAccountByEmailWithPass, getAccountByUsernameWithPass };
declare function addAccountMetadata(accountId: string): Promise<any>;
declare function getAccountMetadata(accountId: string): Promise<any>;
declare function updateAccountsMetadataDistanceUnit(accountId: string, distanceUnit: string): Promise<any>;
declare function updateAccountsMetadataSearchDistance(accountId: string, searchDistance: string): Promise<any>;
declare function updateAccountsMetadataSearchType(accountId: string, searchType: string): Promise<any>;
declare function updateAccountsMetadataMatureFilter(accountId: string, matureFilter: boolean): Promise<any>;
declare function updateAccountsMetadataThemeWeb(accountId: string, themeWeb: boolean): Promise<any>;
declare function addAccount(email: string, username: string, pass: string, phone: string, salt: string): Promise<any>;
declare function getAccountByEmail(email: string): Promise<any>;
declare function getAccountByUsername(username: string): Promise<any>;
declare function getAccountByEmailWithPass(email: string): Promise<any>;
declare function getAccountByUsernameWithPass(username: string): Promise<any>;
declare function getAccountById(id: string): any;
declare function deleteAccount(accountId: string): any;
declare function updateUsername(username: string, accountId: string): any;
declare function usernameExists(username: string): any;
declare function updateEmail(email: string, accountId: string): any;
declare function updatePhone(phone: string, accountId: string): any;
declare function changePassword(account_id: string, password: string, salt: string): any;
declare function verifyAccount(account_id: string, date: Date): any;
declare function getFacebookAccount(facebookId: string): Promise<any>;
declare function addFacebookAccount(id: string, email: string, username: string): Promise<any>;
declare function connectFacebookAccount(facebookId: string, accountId: string): Promise<any>;
declare function disconnectFacebookAccount(accountId: string): Promise<any>;
declare function getGoogleAccount(googleId: string): Promise<any>;
declare function addGoogleAccount(id: string, email: string, username: string): Promise<any>;
declare function connectGoogleAccount(googleId: string, accountId: string): Promise<any>;
declare function disconnectGoogleAccount(accountId: string): Promise<any>;
