declare const _default: {
    getFriends: typeof getFriends;
    getFriendRequests: typeof getFriendRequests;
    addFriendRequest: typeof addFriendRequest;
    acceptFriendRequest: typeof acceptFriendRequest;
    declineFriendRequest: typeof declineFriendRequest;
    deleteFriendById: typeof deleteFriendById;
    friendRequestExists: typeof friendRequestExists;
    getFriendsExist: typeof getFriendsExist;
    getPendingFriendRequests: typeof getPendingFriendRequests;
};
export default _default;
declare function getFriends(accountId: string, date: string, limit: string): any;
declare function getFriendsExist(firstId: string, secondId: string): any;
declare function deleteFriendById(id: string, accountId: string): any;
declare function getFriendRequests(accountId: string): any;
declare function getPendingFriendRequests(accountId: string): any;
declare function friendRequestExists(friendId: string, accountId: string): any;
declare function addFriendRequest(senderId: string, receiverId: string): any;
declare function acceptFriendRequest(id: string, accountId: string): any;
declare function declineFriendRequest(id: string, accountId: string): any;
