declare const _default: {
    getNotificationByReceiverId: typeof getNotificationByReceiverId;
    getNotificationById: typeof getNotificationById;
    addNotification: typeof addNotification;
    deleteNotificationById: typeof deleteNotificationById;
    addCommentNotification: typeof addCommentNotification;
    setAllNotificationsSeen: typeof setAllNotificationsSeen;
    setNotificationSeen: typeof setNotificationSeen;
    deleteAllNotificationsForAccount: typeof deleteAllNotificationsForAccount;
    getNotificationUnreadByReceiverId: typeof getNotificationUnreadByReceiverId;
    addReplyNotification: typeof addReplyNotification;
};
export default _default;
declare function getNotificationByReceiverId(receiverId: string, before: Date | null, after: Date | null, limit: number): any;
declare function getNotificationById(id: string): any;
declare function addNotification(senderId: string, receiverId: string, postId: string): any;
declare function addCommentNotification(senderId: string, receiverId: string, postId: string, commentId: string): any;
declare function addReplyNotification(senderId: string, receiverId: string, postId: string, commentId: string, replyId: string): any;
declare function setNotificationSeen(notificationId: string, accountId: string): any;
declare function setAllNotificationsSeen(accountId: string): any;
declare function deleteNotificationById(id: string, accountId: string): any;
declare function deleteAllNotificationsForAccount(accountId: string): any;
declare function getNotificationUnreadByReceiverId(accountId: string): any;
